language: go

install: true

sudo: required

# test stage automatically added for each go version
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

script:
  - go get github.com/raravena80/gotestsshd
  - go get github.com/raravena80/gotestsshagent
  - go get -t ./...
  - gotestsshd & > /dev/null 2>&1
  - gotestsshagent & > /dev/null 2>&1
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
