language: go

install: true

sudo: required

# test stage automatically added for each go version
go:
  - 1.8.x
  - 1.9.x

jobs:
  fast_finish: true
  include:
    - stage: dependencies
      script: go get -t ./...
    - stage: test
      script:
        - make test
notifications:
  email:
    on_success: change
    on_failure: always
