language: go

install: true

sudo: required

# test stage automatically added for each go version
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

script:
  - go get -t ./...
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
