language: go

install: true

sudo: required

# test stage automatically added for each go version
go:
  - 1.9.x
  - master

env:
  - DEP_VERSION="0.3.2"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go get github.com/raravena80/gotestsshd
  - go get github.com/raravena80/gotestsshagent
  - gotestsshd & > /dev/null 2>&1
  - gotestsshagent & > /dev/null 2>&1
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
